<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net6.0-windows</TargetFramework>
        <Nullable>disable</Nullable>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CC.Core\CC.Core.csproj" />
      <ProjectReference Include="..\CC.Data\CC.Data.csproj" />
      <ProjectReference Include="..\CC.UI\CC.UI.csproj" />
      <ProjectReference Include="..\JsonParser\JsonParser.csproj" />
      <ProjectReference Include="..\SocketManager\SocketManager.csproj" />
    </ItemGroup>

</Project>
