<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MaterialDesignColors" Version="5.2.0" />
      <PackageReference Include="MaterialDesignThemes" Version="5.2.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CC.Data\CC.Data.csproj" />
      <ProjectReference Include="..\JsonParser\JsonParser.csproj" />
      <ProjectReference Include="..\SocketManager\SocketManager.csproj" />
    </ItemGroup>

</Project>
