<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="WindowsAPICodePack-Shell" Version="1.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CC.Core\CC.Core.csproj" />
    </ItemGroup>

</Project>
